### ISSUE TITLE
Symlink in the release tar.gz

### ISSUE THREAD

**Issue by Lambik** [nephelaiio/ansible-role-tmux#1]
Hi,

There seems to be a symlink in the roles/ folder in the tar.gz'ipped file that I get from the galaxy. This causes the ungzip to fail in my shared VM folder. Other roles I've downloaded don't have this roles/ folder, nor the symlink inside. Do you really need to have it? What does it do?

Best regards,
  Tom

**Comment by teddyphreak** [comment]
Hi Tom,
It was a stale resource from the times of molecule < 2.0.0.
I've released version 2.0.3, try that file to see if it works for you; a simple sanity check seems to suggest it should:
`guest@nucz:/tmp$ wget -q https://github.com/nephelaiio/ansible-role-tmux/archive/2.0.3.tar.gz
guest@nucz:/tmp$ tar xzf 2.0.3.tar.gz
guest@nucz:/tmp$ find ansible-role-tmux-2.0.3/ -type l | wc -l
0`

**Comment by Lambik** [comment]
Hi,
Thanks for looking into it! However, on the galaxy "store" the version linked is still 2.0.0 apparently, when trying to get it with `ansible-galaxy install`. Perhaps you could fix that too, for future users?
Thanks!

**Comment by Lambik** [comment]
Oh the error is not with this package (it's 2.0.3 alright), but it's in the dependencies:

- downloading role 'git', owned by nephelaiio
- downloading role from https://github.com/nephelaiio/ansible-role-git/archive/2.0.0.tar.gz
- extracting nephelaiio.git to /mnt/hgfs/ansible/roles/nephelaiio.git
 [WARNING]: - nephelaiio.git was NOT installed successfully: Could not update files in
/mnt/hgfs/ansible/roles/nephelaiio.git: [Errno 95] Operation not supported

**Comment by teddyphreak** [comment]
Good catch, 2.0.5 has updated dependencies without symlinks
